#pragma once

#define DF_CORE_VERSION_MAJOR 0
#define DF_CORE_VERSION_MINOR 0
#define DF_CORE_VERSION_PATCH 1

#define DF_CORE_VERSION_ENCODE(MAJOR, MINOR, PATCH) ((MAJOR<<22)+(MAJOR<<12)+PATCH)
#define DF_CORE_VERSION_DECODE_MAJOR(VERSION) (VERSION>>22)
#define DF_CORE_VERSION_DECODE_MINOR(VERSION) ((VERSION & ((1<<22)-1)) >> 12)
#define DF_CORE_VERSION_DECODE_PATCH(VERSION) (VERSION & ((1<<12)-1))

#define DF_CORE_VERSION DF_CORE_VERSION_ENCODE(DF_CORE_VERSION_MAJOR, DF_CORE_VERSION_MINOR, DF_CORE_VERSION_PATCH)
#define DF_CORE_VERSION_STRING "0.0.1"

